apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  namespace: default
  name: profile-monitor
  labels:
    name: profile-monitor
    release: prometheus
spec:
  selector:
    matchLabels:
      app: profile
  endpoints:
    - port: http

