apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: recommendation-monitor
  namespace: monitoring
  labels:
    name: recommendation-monitor
    release: prometheus
spec:
  selector:
    matchLabels:
      app: recommendation
  endpoints:
    - port: http
