host: 127.0.0.1
http:
  port: 8080
kafka:
  enabled: false
  topic_prefix:
  brokers:
    - http://broker1.com
    - http://broker2.com
cassandra:
  keyspace: profile
  hosts:
    - 127.0.0.1
  username:
  password:
encrypt:
  secret: "xMmz2AWsH4Vmzcidgt2a043394qgnUrI"
