apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name: api-consumer
  namespace: default
  annotations:
    kubernetes.io/ingress.class: kong
username: apiUser
credentials: [apiuser-apikey]
