apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  labels:
    app: profile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: lukasoft/swiperight-profile
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CASSANDRA_HOSTS
              value: cassandra
            - name: KAFKA_ENABLED
              value: "true"
            - name: KAFKA_BROKERS
              value: "192.168.1.240"
