apiVersion: v1
kind: Service
metadata:
  name: profile
  # annotations:
  #   konghq.com/plugins: swiperight-jwt
  labels:
    app: profile
spec:
  selector:
    app: profile
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
