apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-deployment
  labels:
    app: profile
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: profile
  template:
    metadata:
      labels:
        app: profile
    spec:
      containers:
        - name: profile
          image: lukasoft/swiperight-profile
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          env:
            - name: CASSANDRA_HOSTS
              value: cassandra
            - name: CASSANDRA_KEYSPACE
              value: profile
            - name: CASSANDRA_USERNAME
              value:
            - name: CASSANDRA_PASSWORD
              value:
            - name: KAFKA_ENABLED
              value: "true"
            - name: KAFKA_BROKERS
              value: "192.168.1.240"
          resources:
            limits:
              cpu: 1000m
              memory: 1024MiB
            requests:
              cpu: 500m
              memory: 256MiB
