apiVersion: v1
kind: Service
metadata:
  name: recommendation
  annotations:
    konghq.com/plugins: kong-cache
spec:
  selector:
    app: recommendation
  ports:
    - name: http
      protocol: TCP
      port: 8081
