host: 127.0.0.1
http:
  port: 8081
kafka:
  topic: "recommendation"
  brokers:
    - http://broker1.com
    - http://broker2.com
cassandra:
  keyspace: recommendation
  hosts:
    - 127.0.0.1
  username:
  password:
