name: Docker

on:
  push:
    branches: [main]
    paths:
      - "packages/**"

jobs:
  docker:
    environment: docker
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.TOKEN }}
      - name: Build and push Profile
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:packages/profile"
          tags: lukasoft/swiperight-profile:latest
      - name: Build and push Recommendation
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:packages/recommendation"
          tags: lukasoft/swiperight-recommendation:latest


