name: Go

defaults:
  run:
    working-directory: packages/profile

on:
  push:
    branches: [main, staging, development]
    paths:
      - packages/profile/**
  pull_request:
    branches: [main, staging, development]
    paths:
      - packages/profile/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Check Go version
        run: go version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Run vet
        run: go vet .

      - name: Run staticcheck
        uses: dominikh/staticcheck-action@v1.1.0
        with:
          version: "2022.1"
          min-go-version: "1.18"
          install-go: false
          working-directory: packages/profile
          
      - name: Run coverage
        run: go test -race -coverprofile=coverage.out -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2


